name: 'Outline Markdown Sync'
description: 'Sync markdown files from repository to Outline knowledge base'
author: 'xdeca'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  outline_api_key:
    description: 'API key for Outline authentication'
    required: true
  collection_id:
    description: 'Target collection ID in Outline'
    required: true
  outline_base_url:
    description: 'Base URL for Outline (for self-hosted instances)'
    required: false
    default: 'https://app.getoutline.com'
  sync_mode:
    description: 'Sync mode: "changed" (only changed files on PR) or "full" (all files)'
    required: false
    default: 'changed'
  delete_removed:
    description: 'Delete documents from Outline when source files are deleted'
    required: false
    default: 'true'
  file_pattern:
    description: 'Glob pattern for markdown files to sync'
    required: false
    default: '**/*.md'

outputs:
  synced_count:
    description: 'Number of documents created or updated'
    value: ${{ steps.sync.outputs.synced_count }}
  deleted_count:
    description: 'Number of documents deleted'
    value: ${{ steps.sync.outputs.deleted_count }}
  failed_count:
    description: 'Number of operations that failed'
    value: ${{ steps.sync.outputs.failed_count }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ${{ github.action_path }}/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci

    - name: Sync markdown to Outline
      id: sync
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        OUTLINE_API_KEY: ${{ inputs.outline_api_key }}
        OUTLINE_BASE_URL: ${{ inputs.outline_base_url }}
        COLLECTION_ID: ${{ inputs.collection_id }}
        SYNC_MODE: ${{ inputs.sync_mode }}
        DELETE_REMOVED: ${{ inputs.delete_removed }}
        FILE_PATTERN: ${{ inputs.file_pattern }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: node ${{ github.action_path }}/src/index.js
